---
- name: Install k3s server
  hosts: server
  vars:
    eth1_interface: eth1
    node_ip: 192.168.56.110
  tasks:
    - name: Install k3s server
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server --node-ip={{ node_ip }} --advertise-address={{ node_ip }} --write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s token
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: Read k3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_raw

    - name: Set token as fact
      set_fact:
        k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"

- name: Install k3s agents
  hosts: agents
  vars:
    eth1_interface: eth1
    node_ip: 192.168.56.111
    server_node_ip: 192.168.56.110
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://{{ server_node_ip }}:6443 \
        K3S_TOKEN={{ hostvars['dbanfiS'].k3s_token }} \
        INSTALL_K3S_EXEC="--node-ip={{ node_ip }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Configure network interfaces
      copy:
        content: |
          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet dhcp
              post-up route del default dev eth0

          auto eth1
          iface eth1 inet static
              address {{ node_ip }}
              netmask 255.255.255.0
              gateway 192.168.56.1
        dest: /etc/network/interfaces
        backup: yes

    - name: Restart networking service
      service:
        name: networking
        state: restarted

    - name: Wait for network to be ready
      pause:
        seconds: 3
