---
- name: Install k3s server
  hosts: server
  become: true
  vars:
    server_ip: 192.168.56.110
  tasks:
    - name: Install k3s server
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="--node-ip={{ ansible_host }} --advertise-address={{ ansible_host }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s token
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token

    - name: Read k3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token_raw

    - name: Set token as fact
      set_fact:
        k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"

- name: Install k3s agents
  hosts: agents
  become: true
  vars:
    server_ip: 192.168.56.110
  tasks:
    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://{{ server_ip }}:6443 \
        K3S_TOKEN={{ hostvars['dbanfiS'].k3s_token }} \
        INSTALL_K3S_EXEC="--node-ip={{ ansible_host }}" sh -
      args:
        creates: /usr/local/bin/dbanfiSW
