Vagrant.configure("2") do |config|
  # Dynamically fetch latest Alpine version
  alpine_box = `bash ./scripts/get_latest_alpine.sh`.strip
  alpine_box = "generic/alpine319" if alpine_box.empty?  # Fallback
  config.vm.box = alpine_box
  config.vm.box_check_update = false

  # Common provisioning for SSH setup (passwordless between VMs)
  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk add openssh net-tools bash
    rc-update add sshd
    rc-service sshd start
  SHELL


  config.vm.define "dbanfiS" do |server|
    server.vm.hostname = "dbanfiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder "./confs", "/home/vagrant/confs", type: "rsync"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiS"]
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "./scripts/server_setup.sh"
  end
end
