Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04

  # Common provisioning for SSH setup (passwordless between VMs)
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y openssh-server net-tools
    sudo systemctl enable ssh
    sudo systemctl start ssh
  SHELL


  config.vm.define "dbanfiS" do |server|
    server.vm.hostname = "dbanfiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiS"]
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "./scripts/server_setup.sh"
  end
end
