Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"  # Alpine Linux 3.19
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "./scripts/setup.sh"

  config.vm.define "dbanfiS" do |server|
    server.vm.hostname = "dbanfiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiS"]
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "dbanfiSW" do |worker|
    worker.vm.hostname = "dbanfiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiSW"]
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Run Ansible AFTER machines exist
    worker.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "./confs/inventory.yaml"
      ansible.playbook = "./confs/site.yaml"
      ansible.limit = "all"
    end
  end
end
