Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"  # Alpine Linux 3.19
  # Shared folder visible to ALL VMs
  config.vm.synced_folder "./shared", "/vagrant_shared"
  config.trigger.before :up do |t|
    t.info = "Preparing folders"
    t.run = {inline: "sh -c 'mkdir -p ./shared && cp ./scripts/worker_setup.sh ./shared/'"}
  end
  config.trigger.after :destroy do |t|
    t.info = "Cleaning keys"
    t.run = {inline: "rm -f ./shared/*"}
  end 

  # Common provisioning for SSH setup (passwordless between VMs)
  config.vm.provision "shell", inline: <<-SHELL
    apk update
    apk add openssh net-tools bash
    rc-update add sshd
    rc-service sshd start
    sed -i 's/^#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/^PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
    echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
    # Restart SSH service to apply changes
    service sshd restart
  SHELL

  config.vm.define "dbanfiSW" do |worker|
    worker.vm.hostname = "dbanfiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiSW"]
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "./scripts/worker_up.sh"
  end

  config.vm.define "dbanfiS" do |server|
    server.vm.hostname = "dbanfiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "dbanfiS"]
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "./scripts/server_up.sh"
    server.trigger.after :up do |t|
      t.info = "Starting worker setup..."
      t.run = {inline: "vagrant ssh dbanfiSW -- sudo -u k3s-admin bash /vagrant_shared/worker_setup.sh"}
    end
  end
end
