#!/bin/bash

# Load credentials from .env file
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  source "$SCRIPT_DIR/.env"
else
  echo "Error: .env file not found in $SCRIPT_DIR"
  exit 1
fi

# Ensure cleanup of port-forward on script exit
cleanup() {
  echo "Cleaning up port-forward..."
  sudo pkill -f "kubectl port-forward svc/argocd-server" 2>/dev/null
  curl -kLs "https://localhost:8081" 1>/dev/null 2>/dev/null
}
trap cleanup EXIT

# Create the Argo CD namespace and install:
sudo kubectl create namespace argocd
sudo kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Wait for pods to start
sudo kubectl wait --for=condition=Ready pods --all -n argocd --timeout=300s

# Get the initial admin password from the secret (auto-generated by ArgoCD)
INITIAL_PASSWORD=$(sudo kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
echo "Initial ArgoCD password retrieved from secret"

# Forward the port in the background and suppress all output
#sudo kubectl port-forward svc/argocd-server -n argocd 8081:443 >/dev/null 2>&1 &
nohup  $PWD/portForward.sh argocd argocd-server 8081:443 >  $PWD/logs/argocd-portforward.log 2>&1 &
PORT_FORWARD_PID=$!

# Wait for port forwarding to be ready
sleep 5

# Login to ArgoCD using the initial auto-generated password
sudo argocd login localhost:8081 --insecure --username admin --password "$INITIAL_PASSWORD"

# Change password to the one from .env file
echo "Changing ArgoCD password to the one specified in .env file..."

sudo argocd account update-password --current-password "$INITIAL_PASSWORD" --new-password "$ARGOCD_PASSWORD"

echo "ArgoCD password changed successfully"


# to activate the port forwarding again after script ends, run:
# sudo kubectl port-forward svc/argocd-server -n argocd 8081:443

# to view argocd UI, open a browser and go to:
# https://localhost:8081

# Note: The port-forward will be automatically cleaned up when the script exits due to the trap set earlier.